version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Install phase"
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Build phase"
      - npm run build
artifacts:
  files:
    - index.js
    - node_modules/**/*
  discard-paths: yes
